### ISSUE TITLE
Would it be possible to publish the migrations versus running them automatically?

### ISSUE THREAD

**Issue by simensen** [JustSteveKing/laravel-feature-flags#14]
I have an older model/schema that is unable to run the default migration scripts. It uses `$table->increments('id')` instead of `$table->bigIncrements('id')` and this causes the migration to fail for my application.

The "correct" solution for me is probably to go through and upgrade all the columns to be using bigints, but I was hoping to not have to worry about that just yet.

Is there another workaround to get the migrations to not run automatically?

**Comment by JustSteveKing** [comment]
Hey @simensen unfortunately not right now, I just did a trial run and it breaks all my tests trying to move the migrations from boot to publishing. I will keep looking to see if there is another package that does similar I can learn off of.

**Comment by simensen** [comment]
@JustSteveKing Do you have a branch with the work you've done so far? My guess is that you probably need to update the package's `TestCase` class so that it loads migrations from the project directory directly rather than allowing the service provider itself to load them.

```
class TestCase extends Orchestra
{
    protected function setUp(): void
    {
        parent::setUp();

        // Get's you the default `User` model migrations and what not...
        $this->loadLaravelMigrations();

        // Manually loads the migrations from the package... not sure if this path is
        // 100% correct, so it may not work right out of the box. :)
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');
    }
}
```

If this is what you tried already then maybe I can look at your branch to see if I can get it working?

----

FWIW I've created a migration to migrate all my `increments` to `bigIncrements` and it looks like I can run the default migrations now. So, in theory, this isn't a super high priority for me?

I also started a Twitter thread pretty late on a Friday night (so not a lot of discussions yet) about this as I'm now curious what people really expect and whether my default instinct of "I wish this were a migration" is common or not.

https://twitter.com/beausimensen/status/1439031132973056000

**Comment by JustSteveKing** [comment]
I will push a branch as soon as I can, however I have a mental weekend with getting ready to move house - if you can wait I shall do it - or I'm happy to accept PRs for this 🙂

**Comment by JustSteveKing** [comment]
Also, thanks for using this package! Feedback will be useful as I haven't used it myself yet! 

I built it to solve a problem I was going to need to solve, then I moved to a different project!

**Comment by JustSteveKing** [comment]
Hey @simensen please check the latest published version 0.0.1 which I just published. This has solved the issue for you, and updated the README for instructions on publishing.

Let me know how you get on with the package!

**Comment by simensen** [comment]
@JustSteveKing Awesome! I just installed the update and installed the migrations. Everything still works as expected. I'd already written a migration to migrate from `increments` to `bigIncrements` but happy to have the migrations in my project now. :)

Glad this ended up working out for you to be able to do it this way!

Thanks!

**Comment by JustSteveKing** [comment]
Thanks for pointing it out!!
