### ISSUE TITLE
routeMiddlewares -> str_replace

### ISSUE THREAD

**Issue by nmfmcosta** [JustSteveKing/laravel-feature-flags#19]
Hi,

I believe there is a bug on both FeatureMiddleware and GroupMiddleware: str_replace params are out of order, it should be:

```
GroupMiddleware:
$group = str_replace('-', ' ', $group);

FeatureMiddleware:
$feature = str_replace('-', ' ', $feature);
```

**Comment by JustSteveKing** [comment]
Hey @nmfmcosta this was in a PR I just merged, pull down the latest release and this should be fine now! Let me know if you have any further issues 😄
