### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by zaherg** [JustSteveKing/laravel-feature-flags#28]
Hey @JustSteveKing 
I was wondering if you are planning to support Laravel 10, if thats something you want I can try sending you a PR that will add L10 support (if I am not mistaken those are small changes in composer side nothing big)

**Comment by JustSteveKing** [comment]
Hey @zaherg - if I'm honest I hadn't planned on it with the release of Laravel Pennant. 

However I know that this library does have some features not available in Laravel Pennant, so I would happily accept a PR!

You will need composer changes as well as GitHub workflow changes to add the support in CI

**Comment by zaherg** [comment]
thanks @JustSteveKing I'll try to send something soon
